config/routes.rb
Rails.application.routes.draw do

  # Comments
  resources :comments

  # Devise, User
  devise_for :users

  # CodePosts
  resources :code_posts # For EDIT
  get 'code/datatable_ajax', to: 'code_posts#datatable_ajax'
  get 'code/new', to: 'code_posts#new', as: 'new_code'
  get 'code/published', to: 'code_posts#published', as: 'published_code'
  get 'code/edit/:id', to: 'code_posts#edit', as: 'edit_code'

  # Voting
  get 'code/:id/upvote', to: 'code_posts#upvote', as: 'upvote_code'

  # CRUD
  get 'code/:id/delete', to: 'code_posts#destroy', as: 'delete_code'
  get 'code/:id', to: 'code_posts#show', as: 'show_code'
  get 'code/', to: 'code_posts#index', as: 'code'

  root 'code_posts#index' # ROOT
  get '*path', to: 'static_pages#home' # If page not found
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code_language.rb
class CodeLanguage

  # Languages getter
  def self.get_languages
    ["C", "C++", "C#", "Java", "Ruby", "Python", "PHP", "JavaScript",
       "Swift", "Objective-C", "Perl", "Ada", "Lisp"]
  end

  def self.get_languages_modes
    ["c_cpp", "c_cpp", "csharp", "java", "ruby", "python", "php", "javascript",
    "swift", "objectivec", "perl", "ada", "lisp"]
  end

  # Languages count getter
  def self.count
    get_languages.count
  end
end

app/models/code_post.rb
class CodePost < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates_uniqueness_of [:title, :code]
  validates_presence_of [:title, :code]
  scope :available, -> { where(deleted_at: nil) } # Not deleted CodePost scope
  scope :upvoted, -> { order('upvotes DESC') }
  belongs_to :user
  has_many :comments
  
  def should_generate_new_friendly_id?
    title_changed?
  end

  def get_language
    CodeLanguage.get_languages[self.code_language.to_i]
  end

  def get_language_mode_code
    CodeLanguage.get_languages_modes[self.code_language.to_i]
  end

  # User already voted.
  def bit_exists?(id)
    self.bits.include?(id)
  end

  # Add Bit to Code Post.
  def do_upvote(id = nil)
    if !id.nil? # Not nil
      unless bit_exists?(id)
        self.bits << id
        self.save
      end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :code_post
  belongs_to :user

  def user
    User.find(self.user_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:login]

  # Only allow letter, number, underscore and punctuation.
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  has_many :code_posts
  has_many :comments
  
  def is_admin?
    self.user_type == "admin"
  end

  def available_posts_count
    CodePost.available.where(user_id: self.id).count;
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/code_posts_controller.rb
class CodePostsController < ApplicationController
  helper_method :is_owner?, :get_username # Helper method for views
  before_action :authenticate_user!, only: [:new, :edit, :create, :upvote, :destroy]
  before_action :set_code_post, only: [:destroy, :show, :edit, :get_username, :update, :upvote]

  def index
    @code_posts = CodePost.available.upvoted.all # Get all non deleted Code posts
  end

  def datatable_ajax
    render json: CodePostDatatable.new(view_context)
  end

  def upvote
    @code_post.do_upvote(current_user.id)
    respond_to do |format|
      format.js
    end
  end

  def show
    session[:code_post_id] = @code_post.id # Set accessable code post id
    @comments = @code_post.comments # Filter the comments
    @comment = Comment.new # New Comment object
  end

  def published
    # Get all non deleted and published by owner Code Posts
    @code_posts = CodePost.available.where(user_id: current_user).all
    render 'index' # Render default view
  end

  def new
    @code_post = CodePost.new # New Code Post
  end

  def edit
    redirect_to root_path unless is_owner?(@code_post)
  end

  def create
    @code_post = CodePost.new(code_post_params)
    @code_post.user_id = current_user.id # Setting whom will belong to
    @code_post.bits << current_user.id

    respond_to do |format|
      if @code_post.save
        format.html { redirect_to show_code_path(@code_post), notice: "Code created successfully!"}
        format.json { render :show, status: created, location: @code_post }
      else
        format.html { render :new }
        format.json { render json: @code_post.errors, status: :unproccesable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @code_post.update(code_post_params)
        format.html { redirect_to show_code_path(@code_post), notice: "Code updated successfully!"}
        format.json { render :show, status: created, location: @code_post }
      else
        format.html { render :edit }
        format.json { render json: @code_post.errors, status: :unproccesable_entity }
      end
    end
  end

  def destroy
    if is_owner?(@code_post) || current_user.is_admin?
      #@code_post.deleted_at = DateTime.now
      #@code_post.save
      @code_post.destroy
      respond_to do |format|
        format.html { redirect_to code_path, notice: "Code deleted successfully!"}
        format.json { head :no_content }
      end
    else
      redirect_to root_path
    end
  end

  def get_username
      @code_post.user.username.humanize
  end

  private

    # Owner of chosen CodePost?
    def is_owner?(code_post)
      code_post.user_id == current_user.id unless current_user.nil?
    end

    # Setting code_post before action
    def set_code_post
      @code_post = CodePost.friendly.find(params[:id])
    end

    # Strong params
    def code_post_params
      params.require(:code_post).permit(:title, :code,
      :tags, :code_language, :bits => [])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :destroy]

  def index
  end

  def show
  end

  def edit
  end

  # Create comment
  def create
    @comment = Comment.new(comment_params) # New object
    @comment.code_post = CodePost.find(session[:code_post_id]) # Set the id
    @comment.user = current_user
    if @comment.save # Save it
      redirect_to code_post_path(1)
    end
  end

  def update
  end

  def new
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :code_post_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_database_count
    CodePost.available.count
  end

  def is_devise_controller?
    params[:controller].include?("devise");
  end

  def get_logo_text
    ("<b>BIT</b>Slace").html_safe
  end

  def get_logo_text_small
    ("<b>B</b>SL").html_safe
  end
end

app/helpers/code_posts_helper.rb
module CodePostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/code_posts/_comments_show.html.erb
<% @comments.each do |comment| %>
<div class="direct-chat-msg">
    <div class="direct-chat-info clearfix">
        <span class="direct-chat-name pull-left"><%= comment.user.username.humanize %></span>
        <span class="direct-chat-timestamp pull-right"><%= comment.updated_at %></span>
    </div>
    <div class="direct-chat-text pull-right"><%= comment.message %></div>
</div>
<% end %>

app/views/code_posts/_editorscripts.html.erb
<!-- <script src="src/ace.js" type="text/javascript" charset="utf-8"></script> -->
<script>
  var editor = ace.edit("editor");
  var textarea = $('#code_post_code');
  editor.setTheme("ace/theme/eclipse");
  editor.getSession().setMode("ace/mode/<%= @code_post.get_language_mode_code %>");
  editor.setShowPrintMargin(false);
  editor.getSession().on('change', function () {
    textarea.val(editor.getSession().getValue());
  });
  textarea.val(editor.getSession().getValue());
</script>

app/views/code_posts/_form.html.erb
<%= simple_form_for(@code_post) do |f| %>
<section class="content">
    <div class="row">
        <div class="col-xs-8">
            <div class="box">
                <div id="editor"><%= @code_post.code %></div>
                <textarea name="code_post[code]" id="code_post_code" hidden="true"><%= @code_post.code %></textarea>
            </div>
        </div>
        <div class="col-xs-4">
            <div class="box box-default">
                <div class="box-header">
                    <h3 class="box-title"><%= fa_icon "question-circle-o", text: " Other information" %></h3>
                    <%= render 'layouts/collapsers' %>
                </div>
                <div class="box-body">
                    <div class="table-responsive">
                        <table class="table no-margin">
                            <tr>
                                <td align="right" width="10%"><%= fa_icon "laptop"%></td>
                                <td>Title</td>
                                <td><%= f.input :title, label: false, input_html: { style:'width:100%' } %></td>
                            </tr>
                            <tr>
                                <td align="right"><%= fa_icon "tags"%></td>
                                <td>Tags</td>
                                <td><%= f.input :tags, label: false, input_html: { style:'width:100%' } %></td>
                            </tr>
                            <tr>
                                <td align="right"><%= fa_icon "code"%></td>
                                <td>Language</td>
                                <td>
                                    <%= f.select :code_language, CodeLanguage.get_languages.each_with_index.map { |name, index| [name, index] }, {}, style: 'width:100%' %>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="box-footer">
                    <%= f.button :submit, "Submit" %>
                </div>
            </div>
        </div>
    </div>
</section>
<% end %>

app/views/code_posts/_info_table.html.erb
<table class="table">
    <tr>
        <td align="right"><%= fa_icon "tags"%></td>
        <td>Tags</td>
        <td><%= @code_post.tags %></td>
    </tr>
    <tr>
        <td align="right" width="10%"><%= fa_icon "diamond"%></td>
        <td>Bits</td>
        <td><%= @code_post.bits.length %>
            <% unless current_user.nil? %>
            <% if !@code_post.bit_exists?(current_user.id) %>
            <div class="pull-right" style="padding-right:10px;">
                <%= link_to upvote_code_path(@code_post), remote: true do %>
                Assign My BIT!
                <% end %>
            </div>
            <% end %>
            <% end %>
        </td>
    </tr>
    <tr>
        <td align="right"><%= fa_icon "code"%></td>
        <td>Language</td>
        <td><%= @code_post.get_language %></td>
    </tr>
    <tr>
        <td align="right"><%= fa_icon "upload"%></td>
        <td>Owner</td>
        <td><%= get_username %></td>
    </tr>
</table>

app/views/code_posts/edit.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <%= render 'layouts/alerts' %>

  <section class="content-header">
    <h1><%= @code_post.title %></h1>
    <ol class="breadcrumb">
      <li><a href="<%= root_path %>">
        <%= fa_icon "clone", text: "Home" %>
        </a>
      </li>
      <li><a href="<%= code_path %>">Database</a></li>
      <li class="active"><a href="<%= show_code_path(@code_post) %>"><%= @code_post.id %></a> (EDIT)</li>
    </ol>
  </section>

<%= render 'form' %>

</div>
<!-- /.content-wrapper -->

<%= render 'editorscripts' %>

app/views/code_posts/index.html.erb
<div class="content-wrapper">
    <%= render 'layouts/alerts' %>

    <section class="content-header">
        <br>
        <ol class="breadcrumb">
            <li>
                <a href="<%= root_path %>">
                    <%= fa_icon "clone", text: "Home" %>
                </a>
            </li>
            <li class="active">Database</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body">
                        <table id="database-table" class="display responsive no-wrap" width="100%">
                            <thead>
                                <tr>
                                    <th><%= fa_icon "diamond"%>
                                        Bits</th>
                                    <th><%= fa_icon "code"%>
                                        Language</th>
                                    <th><%= fa_icon "newspaper-o"%>
                                        Title</th>
                                    <th><%= fa_icon "tags"%>
                                        Tags</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                            <tfoot>
                                <tr>
                                    <th><%= fa_icon "diamond"%>
                                        Bits</th>
                                    <th><%= fa_icon "code"%>
                                        Language</th>
                                    <th><%= fa_icon "newspaper-o"%>
                                        Title</th>
                                    <th><%= fa_icon "tags"%>
                                        Tags</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<script>
    $('#database-table').DataTable({
        "columns": [
            {
                "width": "8%"
            }, {
                "width": "12%"
            }, {
                "width": "40%"
            },
            null
        ],
        "responsive": true,
        "processing": true,
        "serverSide": true,
        "ajax": "code/datatable_ajax/"
    });
</script>

app/views/code_posts/new.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <%= render 'layouts/alerts' %>
  <section class="content-header">
    <h1>Publish Code</h1>
    <ol class="breadcrumb">
      <li><a href="<%= root_path %>">
        <%= fa_icon "clone", text: "Home" %>
        </a>
      </li>
      <li><a href="<%= code_path %>">Database</a></li>
      <li class="active">(NEW)</li>
    </ol>
  </section>

<%= render 'form' %>

</div>
<!-- /.content-wrapper -->

<%= render 'editorscripts' %>

app/views/code_posts/show.html.erb
<div class="content-wrapper">
    <%= render 'layouts/alerts' %>

    <section class="content-header">
        <h1><%= @code_post.title %><% if !current_user.nil? && (is_owner?(@code_post) || current_user.is_admin?) %>
            <%= link_to edit_code_path(@code_post) do %>
            <%= fa_icon "pencil" %>
            <% end %>
            <% end %></h1>
        <ol class="breadcrumb">
            <li>
                <a href="<%= root_path %>">
                    <%= fa_icon "clone", text: "Home" %>
                </a>
            </li>
            <li>
                <a href="<%= code_path %>">Database</a>
            </li>
            <li class="active"><%= @code_post.slug %>
                (VIEW)</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-8">
                <div class="box box-default">
                    <div id="editor"><%= cache @code_post.code do %><%= @code_post.code %><% end %></div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="box box-default">
                    <div class="box-header">
                        <h3 class="box-title"><%= fa_icon "question-circle-o", text: " Other information" %></h3>
                        <%= render 'layouts/collapsers' %>
                    </div>
                    <div class="box-body">
                        <div class="table-responsive">
                            <div id="reputation-ajax">
                                <%= render 'info_table' %>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box box-default">
                    <div class="box-header">
                        <h3 class="box-title"><%= fa_icon "comments", text: " Comments" %></h3>
                        <%= render 'layouts/collapsers' %>
                    </div>
                    <div class="box-body">
                        <%= render 'comments/form' %>
                        <div class="table-responsive">
                            <%= render 'comments_show' %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<%= render 'editorscripts' %>

app/views/code_posts/upvote.js.erb
$("#reputation-ajax").html("<%= escape_javascript(render 'info_table') %>");

app/views/comments/_form.html.erb
<% unless current_user.nil? %>
<%= simple_form_for(@comment) do |f| %>
<div class="input-group" style="margin-bottom:15px;">
    <%= f.input :message, label: false, placeholder: "Type Message...", input_html: { class: 'form-control' }, as: :string %>
    <span class="input-group-btn">
        <%= f.button :submit, "Comment", class: "btn btn-default btn-flat" %>
    </span>
</div>
<% end %>
<% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/_alerts.html.erb
<!-- Alerts -->
<!-- <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->
<%#= notice %>
<%#= alert %>

<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
  <% if name == "alert" %>
  <div class="alert alert-danger" id="alert_message" style="margin:10px;">
  <% else %>
  <div class="alert alert-success" id="alert_message" style="margin:10px;">
  <% end %>
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
  </div>
  <% end %>
<% end %>

app/views/layouts/_collapsers.html.erb
<div class="box-tools pull-right">
  <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
  </button>
</div>

app/views/layouts/_content.html.erb
<%= yield %>

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <strong>&copy; Ugnius Skučas <%= DateTime.now.year %></strong>
  <div class="pull-right hidden-xs">
    <b>Version</b> 0.0.1
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="main-header">
  <a href="<%= root_path %>" class="logo">
    <span class="logo-mini"><%= fa_icon "clone" %></span>
    <span class="logo-lg"><%= fa_icon "clone" %> <%= get_logo_text %></span>
  </a>
  <nav class="navbar navbar-static-top">
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav navbar-left">
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>

      <li>
        <a href="<%= code_path %>">
          <i class="fa fa-table"></i>
          <span>Database (<%= get_database_count %>)</span></a>
      </li>

      <li class="header">USER NAVIGATION</li>
      <% unless current_user.nil? # LOGGED IN%>
      <li>
        <a href="<%= new_code_path %>">
          <%= fa_icon "edit" %>
          <span>Publish Code</span></a>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <%= fa_icon "sign-out" %>
          <span>Logout</span>
        <% end %>
      </li>
      <% else # LOGGED OFF %>
      <li>
        <%= link_to new_user_session_path do %>
          <%= fa_icon "sign-in" %>
          <span>Sign in</span>
        <% end %>
      </li>
      <li>
        <%= link_to new_user_registration_path do %>
          <%= fa_icon "lock" %>
          <span>Registration</span>
        <% end %>
      </li>
      <% end %>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BITSlace</title>
  <%= favicon_link_tag '/favicon.ico' %>
  <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<% unless is_devise_controller? # MAIN APPLICATION %>
  <body class="fixed hold-transition skin-black sidebar-mini">
    <div class="wrapper">
      <%= render 'layouts/header' %>
      <%= render 'layouts/sidebar' %>
      <%= render 'layouts/content' %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
<% else #FOR LOGIN/SIGNUP %>
  <%= render 'layouts/alerts' %>
  <%= render 'layouts/content' %>
<% end %>
</html>

<!-- Infolinks integration -->

<script type="text/javascript">
  var infolinks_pid = 2920300;
  var infolinks_wsid = 0;
</script>
<script type="text/javascript" src="http://resources.infolinks.com/js/infolinks_main.js"></script>